import type { Article } from "./data";

export const mockArticles: Article[] = [
  // ── Technology ──────────────────────────────────────────────
  {
    id: "t1",
    title: "The Rise of Autonomous AI Agents in Enterprise Software",
    excerpt: "Major tech companies are deploying AI agents that can independently plan, execute, and iterate on complex business workflows — raising questions about accountability and control.",
    category: "technology",
    contentType: "article",
    date: "2026-03-17",
    author: "Elena Vasquez",
    readTime: "6 min",
    trending: true,
  },
  {
    id: "t2",
    title: "Quantum-Safe Encryption Standards Finally Arrive",
    excerpt: "NIST's newly ratified post-quantum cryptographic algorithms are now being adopted by cloud providers worldwide, marking a pivotal shift in cybersecurity infrastructure.",
    category: "technology",
    contentType: "video",
    date: "2026-03-15",
    author: "David Kim",
    readTime: "18 min",
  },
  {
    id: "t3",
    title: "Inside the Race to Build Neuromorphic Chips",
    excerpt: "A new generation of processors modeled on the human brain promises radically lower power consumption and faster inference — but the engineering challenges remain daunting.",
    category: "technology",
    contentType: "podcast",
    date: "2026-03-12",
    author: "Priya Ramachandran",
    readTime: "47 min",
    trending: true,
  },
  {
    id: "t4",
    title: "The Innovator's Dilemma Revisited: AI Edition",
    excerpt: "Clayton Christensen's seminal framework gets a 2026 update examining how generative AI is disrupting the disruptors themselves — from cloud giants to Silicon Valley startups.",
    category: "technology",
    contentType: "book",
    date: "2026-03-08",
    author: "Dr. Michael Torres",
    readTime: "312 pages",
  },

  // ── Media ───────────────────────────────────────────────────
  {
    id: "m1",
    title: "How Spatial Computing Is Redefining Broadcast Media",
    excerpt: "With mixed-reality headsets reaching mainstream adoption, broadcasters are reimagining the living room as a three-dimensional news stage with interactive data overlays.",
    category: "media",
    contentType: "video",
    date: "2026-03-17",
    author: "Marcus Chen",
    readTime: "12 min",
  },
  {
    id: "m2",
    title: "The Newsletter Renaissance: Why Long-Form Email Is Thriving",
    excerpt: "Despite predictions of email's demise, independent newsletters are generating more revenue and reach than ever, challenging traditional media economics and newsroom models.",
    category: "media",
    contentType: "article",
    date: "2026-03-14",
    author: "Rachel Osei",
    readTime: "6 min",
    trending: true,
  },
  {
    id: "m3",
    title: "Synthetic Anchors: The Ethics of AI-Generated News Presenters",
    excerpt: "Several Asian broadcasters now use entirely AI-generated anchors for 24/7 news coverage. Western outlets are watching closely — and ethicists are sounding alarms.",
    category: "media",
    contentType: "podcast",
    date: "2026-03-10",
    author: "Tomoko Ishida",
    readTime: "38 min",
  },
  {
    id: "m4",
    title: "Attention Factory: How TikTok Rewired Global Media",
    excerpt: "An exhaustive investigation into how short-form video reshaped content creation, journalism, and the very concept of a media company in less than a decade.",
    category: "media",
    contentType: "book",
    date: "2026-03-05",
    author: "Alexei Volkov",
    readTime: "288 pages",
  },

  // ── Communication ──────────────────────────────────────────
  {
    id: "c1",
    title: "The Collapse of Context: Communication in the Age of Fragments",
    excerpt: "As attention spans shrink and messaging platforms multiply, scholars warn that shared context — the foundation of meaningful dialogue — is eroding faster than ever.",
    category: "communication",
    contentType: "article",
    date: "2026-03-16",
    author: "Aisha Patel",
    readTime: "7 min",
    trending: true,
  },
  {
    id: "c2",
    title: "Asynchronous Communication and the Death of the Meeting",
    excerpt: "Leading remote-first companies are eliminating real-time meetings entirely. Their communication protocols offer a glimpse at the future of distributed work.",
    category: "communication",
    contentType: "video",
    date: "2026-03-13",
    author: "Lin Wei",
    readTime: "22 min",
  },
  {
    id: "c3",
    title: "How Language Models Are Changing Corporate Rhetoric",
    excerpt: "From earnings calls to internal memos, executives are increasingly relying on AI-drafted communications — homogenizing corporate language and raising authenticity concerns.",
    category: "communication",
    contentType: "podcast",
    date: "2026-03-09",
    author: "Carla Mendes",
    readTime: "51 min",
  },
  {
    id: "c4",
    title: "The Empathy Gap: Digital Communication and Emotional Intelligence",
    excerpt: "A comprehensive study exploring how screen-mediated interaction is reshaping our capacity for empathy, active listening, and nuanced emotional expression.",
    category: "communication",
    contentType: "book",
    date: "2026-03-03",
    author: "Dr. Sarah Lindqvist",
    readTime: "264 pages",
  },

  // ── Philosophy ─────────────────────────────────────────────
  {
    id: "p1",
    title: "Digital Consciousness and the Hard Problem: A 2026 Reassessment",
    excerpt: "New research in computational neuroscience reopens the debate on whether silicon substrates can produce genuine subjective experience — or merely simulate it.",
    category: "philosophy",
    contentType: "article",
    date: "2026-03-16",
    author: "Prof. James Whitmore",
    readTime: "9 min",
    trending: true,
  },
  {
    id: "p2",
    title: "Wittgenstein's Ghost in the Machine Learning Pipeline",
    excerpt: "Language models process words without understanding meaning — a tension the philosopher anticipated nearly a century ago. What can his later work teach AI researchers?",
    category: "philosophy",
    contentType: "podcast",
    date: "2026-03-14",
    author: "Dr. Hannah Meier",
    readTime: "44 min",
  },
  {
    id: "p3",
    title: "Justice in the Algorithm: Rawls Meets Recommender Systems",
    excerpt: "If algorithms allocate opportunity, attention, and resources, should they satisfy Rawlsian fairness criteria? A philosopher and an engineer debate the question.",
    category: "philosophy",
    contentType: "video",
    date: "2026-03-11",
    author: "Prof. Amara Okafor",
    readTime: "28 min",
  },
  {
    id: "p4",
    title: "Techne and Telos: Technology as a Philosophical Category",
    excerpt: "Tracing the concept of technology from Aristotle through Heidegger to the present day, this work argues for a renewed philosophical engagement with our tools.",
    category: "philosophy",
    contentType: "book",
    date: "2026-03-01",
    author: "Dr. Konstantin Petrov",
    readTime: "340 pages",
  },

  // ── Advertising ────────────────────────────────────────────
  {
    id: "a1",
    title: "Programmatic Creativity: When Algorithms Become Art Directors",
    excerpt: "The latest generation of AI creative tools is blurring the line between strategic media buying and original creative production in global ad agencies.",
    category: "advertising",
    contentType: "article",
    date: "2026-03-15",
    author: "Sofia Andersson",
    readTime: "5 min",
  },
  {
    id: "a2",
    title: "Attention Markets: The True Currency of Digital Advertising",
    excerpt: "A new measurement framework proposes replacing impressions with verified attention seconds, threatening to upend the $600B digital ad industry.",
    category: "advertising",
    contentType: "video",
    date: "2026-03-13",
    author: "Tom Bradley",
    readTime: "16 min",
    trending: true,
  },
  {
    id: "a3",
    title: "The Brand Voice Paradox: Authenticity in an AI-Written World",
    excerpt: "As brands adopt generative AI for copywriting at scale, consumers are paradoxically craving more human, imperfect, and emotionally resonant messaging.",
    category: "advertising",
    contentType: "podcast",
    date: "2026-03-07",
    author: "Jenna Liu",
    readTime: "36 min",
  },
  {
    id: "a4",
    title: "Subprime Attention Crisis: Advertising and the Time Bomb at the Heart of the Internet",
    excerpt: "An updated edition of the influential critique arguing that digital advertising's metrics are fundamentally unreliable — and the reckoning is closer than we think.",
    category: "advertising",
    contentType: "book",
    date: "2026-02-28",
    author: "Tim Hwang",
    readTime: "296 pages",
  },
];
