import { useState } from "react";
import { Coffee, Sun, Moon } from "lucide-react";
import { useDailyBriefs, type Session } from "@/hooks/use-morning-brief";

const SESSION_ORDER: Session[] = ["morning", "afternoon", "evening"];

const SESSION_META: Record<Session, { label: string; time: string; icon: typeof Coffee }> = {
  morning: { label: "Morning", time: "08:00", icon: Coffee },
  afternoon: { label: "Afternoon", time: "13:00", icon: Sun },
  evening: { label: "Evening", time: "19:00", icon: Moon },
};

function getCurrentSession(): Session {
  const hour = new Date().getUTCHours();
  if (hour < 13) return "morning";
  if (hour < 19) return "afternoon";
  return "evening";
}

function parseBold(text: string) {
  const parts = text.split(/\*\*(.*?)\*\*/g);
  return parts.map((part, i) =>
    i % 2 === 1 ? <strong key={i} className="font-semibold">{part}</strong> : part
  );
}

function parseBullets(content: string) {
  return content
    .split("•")
    .map((s) => s.trim())
    .filter(Boolean);
}

export function MorningBriefSection() {
  const { data: briefs, isLoading } = useDailyBriefs();
  const [lang, setLang] = useState<"en" | "tr">("en");
  const [activeSession, setActiveSession] = useState<Session | null>(null);

  if (isLoading || !briefs || briefs.length === 0) return null;

  const availableSessions = briefs.map((b) => b.session as Session);
  const currentSession = activeSession && availableSessions.includes(activeSession)
    ? activeSession
    : availableSessions[availableSessions.length - 1];

  const currentBrief = briefs.find((b) => b.session === currentSession);
  if (!currentBrief) return null;

  const content = lang === "en" ? currentBrief.content_en : currentBrief.content_tr;
  const bullets = parseBullets(content);
  const meta = SESSION_META[currentSession];
  const Icon = meta.icon;

  const today = new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  return (
    <section className="border-b border-border">
      <div className="container py-10">
        <div className="rounded-xl p-6 md:p-8" style={{ backgroundColor: "hsl(34 33% 92%)" }}>
          {/* Header */}
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <Icon className="h-5 w-5 text-primary" />
              <span className="font-display text-lg font-bold tracking-tight">Daily Brief</span>
            </div>
            <div className="flex items-center gap-3">
              <span className="text-sm text-muted-foreground hidden sm:inline">{today}</span>
              <div className="flex rounded-full border border-border bg-card p-0.5">
                <button
                  onClick={() => setLang("en")}
                  className={`rounded-full px-3 py-1 text-xs font-semibold transition-colors ${
                    lang === "en"
                      ? "bg-primary text-primary-foreground"
                      : "text-muted-foreground hover:text-foreground"
                  }`}
                >
                  EN
                </button>
                <button
                  onClick={() => setLang("tr")}
                  className={`rounded-full px-3 py-1 text-xs font-semibold transition-colors ${
                    lang === "tr"
                      ? "bg-primary text-primary-foreground"
                      : "text-muted-foreground hover:text-foreground"
                  }`}
                >
                  TR
                </button>
              </div>
            </div>
          </div>

          {/* Session tabs */}
          {availableSessions.length > 1 && (
            <div className="flex gap-2 mb-6">
              {availableSessions.map((session) => {
                const sm = SESSION_META[session];
                return (
                  <button
                    key={session}
                    onClick={() => setActiveSession(session)}
                    className={`rounded-lg px-3 py-1.5 text-xs font-medium transition-colors ${
                      currentSession === session
                        ? "bg-primary text-primary-foreground"
                        : "bg-card text-muted-foreground hover:text-foreground border border-border"
                    }`}
                  >
                    {sm.label} · {sm.time}
                  </button>
                );
              })}
            </div>
          )}

          {/* Bullets */}
          <ul className="space-y-3">
            {bullets.map((bullet, i) => (
              <li key={i} className="flex gap-3 text-sm leading-relaxed text-foreground">
                <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                <span>{parseBold(bullet)}</span>
              </li>
            ))}
          </ul>

          {/* Footer note */}
          <p className="mt-6 text-xs text-muted-foreground">
            Generated by AI · Updated 3× daily
          </p>
        </div>
      </div>
    </section>
  );
}
