import { useState } from "react";
import { Coffee } from "lucide-react";
import { useMorningBrief } from "@/hooks/use-morning-brief";

function parseBold(text: string) {
  const parts = text.split(/\*\*(.*?)\*\*/g);
  return parts.map((part, i) =>
    i % 2 === 1 ? <strong key={i} className="font-semibold">{part}</strong> : part
  );
}

function parseBullets(content: string) {
  return content
    .split("•")
    .map((s) => s.trim())
    .filter(Boolean);
}

export function MorningBriefSection() {
  const { data: brief, isLoading } = useMorningBrief();
  const [lang, setLang] = useState<"en" | "tr">("en");

  if (isLoading || !brief) return null;

  const content = lang === "en" ? brief.content_en : brief.content_tr;
  const bullets = parseBullets(content);

  const today = new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  return (
    <section className="border-b border-border">
      <div className="container py-10">
        <div className="rounded-xl p-6 md:p-8" style={{ backgroundColor: "hsl(34 33% 92%)" }}>
          {/* Header */}
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-2">
              <Coffee className="h-5 w-5 text-primary" />
              <span className="font-display text-lg font-bold tracking-tight">Morning Brief</span>
            </div>
            <div className="flex items-center gap-3">
              <span className="text-sm text-muted-foreground hidden sm:inline">{today}</span>
              <div className="flex rounded-full border border-border bg-card p-0.5">
                <button
                  onClick={() => setLang("en")}
                  className={`rounded-full px-3 py-1 text-xs font-semibold transition-colors ${
                    lang === "en"
                      ? "bg-primary text-primary-foreground"
                      : "text-muted-foreground hover:text-foreground"
                  }`}
                >
                  EN
                </button>
                <button
                  onClick={() => setLang("tr")}
                  className={`rounded-full px-3 py-1 text-xs font-semibold transition-colors ${
                    lang === "tr"
                      ? "bg-primary text-primary-foreground"
                      : "text-muted-foreground hover:text-foreground"
                  }`}
                >
                  TR
                </button>
              </div>
            </div>
          </div>

          {/* Bullets */}
          <ul className="space-y-3">
            {bullets.map((bullet, i) => (
              <li key={i} className="flex gap-3 text-sm leading-relaxed text-foreground">
                <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                <span>{parseBold(bullet)}</span>
              </li>
            ))}
          </ul>

          {/* Footer note */}
          <p className="mt-6 text-xs text-muted-foreground">
            Generated by AI · Updated daily
          </p>
        </div>
      </div>
    </section>
  );
}
